### PR TITLE
better way of doing it?

### PR DESCRIPTION
**Pull request by ferdna**
this way the file looks as close as possible to the one on slackbuilds. I didnt get why you were doing "${LAME:-yes}" != "yes", i believe you were doing the same thing as "${LAME:-no}" != "no" except the opposite case, maybe you were trying to do something else? anyways i hope you like the changes. =)

### CODE REVIEW

**Comment by ryanpcmcquen** [comment]
We should use this format, so they can be overwritten by the environment/arguments:
`LAME=${LAME:-yes}`

**Comment by ferdna** [comment]
what i am trying to tell you is that it is the same thing:

ex1:
if LAME is not equal to "no" then mp3lame="--enable-libmp3lame"
mp3lame=""    ; [ "${LAME:-no}" != "no" ]         && mp3lame="--enable-libmp3lame"

on example1, mp3lame changed from "" to "--enable-libmp3lame" if yes was passed to the variable.

ex2:
if LAME is not equal to "yes" then mp3lame=""
mp3lame="--enable-libmp3lame" ; [ "${LAME:-yes}" != "yes" ]   && mp3lame=""

on example2, mp3lame STAYED the same ("--enable-libmp3lame") to "" if other than "yes" was passed to the variable.

**Comment by ryanpcmcquen** [comment]
I agree with that, I just want to change this section:

```shell
## ryan's custom settings:
LAME=yes
X264=yes
SPEEX=yes
OPENAL=yes
WEBP=yes
```

To:
```shell
## Ryan's custom settings:
LAME=${LAME:-yes}
X264=${X264:-yes}
SPEEX=${SPEEX:-yes}
OPENAL=${OPENAL:-yes}
WEBP=${WEBP:-yes}
```

http://www.tldp.org/LDP/abs/html/parameter-substitution.html

**Comment by ferdna** [comment]
super cool. I just learned something new today. i am by no means an expert on shell scripting. according to the parameter substitution manual page you don't need the main variable ex. LAME=, X264=,etc...

just having ${LAME:-yes}, ${X264:-yes} will suffice.

```
${LAME:-yes}
${X264:-yes}
${SPEEX:-yes}
${OPENAL:-yes}
${WEBP:-yes}
```

correct me if i am wrong. :)

**Comment by ryanpcmcquen** [comment]
The manual is a little confusing, that will actually expand to:
```shell
yes
yes
yes
yes
yes
```
Which would just run the `yes` command, so the variable assignment (`LAME=`) is necessary.

**Comment by ferdna** [comment]
just tested and you are right! good catch.

**Comment by ryanpcmcquen** [comment]
Would you mind rebasing this PR with those changes?

**Pull request merged**
